apiVersion: v1
kind: Service
metadata:
  name: ac-uf-data-api-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: ac-uf-data-api-pod